set shell := ["bash", "-euo", "pipefail", "-c"]

project_root := justfile_directory()
scratch_root := project_root + "/.scratch/feature-ci"
feature_project_root := scratch_root + "/project"
package_output_root := scratch_root + "/package"
shim_dir := scratch_root + "/bin"
workflow_file := project_root + "/.github/workflows/test.yaml"
workflow_base_image := env_var_or_default("BASE_IMAGE", "registry.access.redhat.com/hi/core-runtime:latest-builder")
workflow_remote_user := env_var_or_default("REMOTE_USER", "root")
homebrew_ci_base_image := env_var_or_default("HOME_BREW_CI_BASE_IMAGE", "feature-ci/homebrew-packages-base:latest")
homebrew_ci_base_containerfile := project_root + "/test/homebrew-packages/feature-ci-base/Containerfile"
xdg_runtime_dir := env_var_or_default("XDG_RUNTIME_DIR", scratch_root + "/xdg")
podman_socket_path := xdg_runtime_dir + "/podman/podman.sock"
podman_service_log_file := scratch_root + "/podman-system-service.log"
act_runner_image := env_var_or_default("ACT_RUNNER_IMAGE", "ghcr.io/catthehacker/ubuntu:act-latest")
act_tmp_dir := scratch_root + "/tmp"
feature_ci_env := "PATH=\"" + shim_dir + ":$PATH\" FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true XDG_RUNTIME_DIR=\"" + xdg_runtime_dir + "\""
act_env := "DOCKER_HOST=\"unix://" + podman_socket_path + "\" " + feature_ci_env + " TMPDIR=\"" + act_tmp_dir + "\" TMP=\"" + act_tmp_dir + "\" TEMP=\"" + act_tmp_dir + "\""

default:
    @just --list

prepare: check-feature-tools prepare-feature-project prepare-runtime
    @printf 'feature-ci scratch workspace ready at %s\n' "{{scratch_root}}"

ci: check-act-tools prepare-runtime
    @podman_service_pid=''; \
    if [ ! -S "{{podman_socket_path}}" ] || ! podman --url "unix://{{podman_socket_path}}" info >/dev/null 2>&1; then \
        rm -f "{{podman_socket_path}}"; \
        nohup podman system service --time=0 "unix://{{podman_socket_path}}" >"{{podman_service_log_file}}" 2>&1 & \
        podman_service_pid=$!; \
        trap 'if [ -n "$podman_service_pid" ]; then kill "$podman_service_pid" 2>/dev/null || true; fi' EXIT; \
        for _ in 1 2 3 4 5 6 7 8 9 10; do \
            if podman --url "unix://{{podman_socket_path}}" info >/dev/null 2>&1; then \
                break; \
            fi; \
            sleep 1; \
        done; \
        if ! podman --url "unix://{{podman_socket_path}}" info >/dev/null 2>&1; then \
            printf 'feature-ci: podman service did not become ready, see %s\n' "{{podman_service_log_file}}" >&2; \
            exit 1; \
        fi; \
    fi; \
    {{act_env}} act workflow_dispatch --bind --env TMPDIR="{{act_tmp_dir}}" --env TMP="{{act_tmp_dir}}" --env TEMP="{{act_tmp_dir}}" --workflows "{{workflow_file}}" -P ubuntu-latest="{{act_runner_image}}"

job job_name: check-act-tools prepare-runtime
    @podman_service_pid=''; \
    if [ ! -S "{{podman_socket_path}}" ] || ! podman --url "unix://{{podman_socket_path}}" info >/dev/null 2>&1; then \
        rm -f "{{podman_socket_path}}"; \
        nohup podman system service --time=0 "unix://{{podman_socket_path}}" >"{{podman_service_log_file}}" 2>&1 & \
        podman_service_pid=$!; \
        trap 'if [ -n "$podman_service_pid" ]; then kill "$podman_service_pid" 2>/dev/null || true; fi' EXIT; \
        for _ in 1 2 3 4 5 6 7 8 9 10; do \
            if podman --url "unix://{{podman_socket_path}}" info >/dev/null 2>&1; then \
                break; \
            fi; \
            sleep 1; \
        done; \
        if ! podman --url "unix://{{podman_socket_path}}" info >/dev/null 2>&1; then \
            printf 'feature-ci: podman service did not become ready, see %s\n' "{{podman_service_log_file}}" >&2; \
            exit 1; \
        fi; \
    fi; \
    {{act_env}} act workflow_dispatch --bind --env TMPDIR="{{act_tmp_dir}}" --env TMP="{{act_tmp_dir}}" --env TEMP="{{act_tmp_dir}}" --workflows "{{workflow_file}}" --job "{{job_name}}" -P ubuntu-latest="{{act_runner_image}}"

feature +features: prepare
    @base_image="{{workflow_base_image}}"; \
    if [[ " {{features}} " == *" homebrew-packages "* ]]; then \
        {{feature_ci_env}} docker build -f "{{homebrew_ci_base_containerfile}}" -t "{{homebrew_ci_base_image}}" "{{project_root}}"; \
        base_image="{{homebrew_ci_base_image}}"; \
    fi; \
    {{feature_ci_env}} devcontainer features test --project-folder "{{feature_project_root}}" --skip-autogenerated --skip-duplicated --base-image "$base_image" --remote-user "{{workflow_remote_user}}" -f {{features}}

podman-in-podman-smoke: prepare
    {{feature_ci_env}} test/podman-in-podman/devcontainer-cli-smoke.sh

publish-check: prepare
    @rm -rf "{{package_output_root}}"
    {{feature_ci_env}} devcontainer features package "{{project_root}}/devcontainer-features" --output-folder "{{package_output_root}}" --force-clean-output-folder
    test -f "{{package_output_root}}/devcontainer-collection.json"

all:
    just ci
    just publish-check

[private]
check-feature-tools:
    @for tool in bash devcontainer jq podman; do \
        command -v "$tool" >/dev/null 2>&1 || { printf 'feature-ci: missing required tool: %s\n' "$tool" >&2; exit 1; }; \
    done

[private]
check-act-tools:
    @for tool in bash act podman; do \
        command -v "$tool" >/dev/null 2>&1 || { printf 'feature-ci: missing required tool: %s\n' "$tool" >&2; exit 1; }; \
    done

[private]
prepare-feature-project:
    @mkdir -p "{{feature_project_root}}"
    @rm -rf "{{feature_project_root}}/src" "{{feature_project_root}}/test"
    @cp -a "{{project_root}}/devcontainer-features" "{{feature_project_root}}/src"
    @cp -a "{{project_root}}/test" "{{feature_project_root}}/test"

[private]
prepare-runtime:
    @mkdir -p "{{shim_dir}}" "{{xdg_runtime_dir}}/podman" "{{act_tmp_dir}}"
    @ln -sf "$(command -v podman)" "{{shim_dir}}/docker"
    @if [ ! -S "{{podman_socket_path}}" ]; then \
        rm -f "{{podman_socket_path}}"; \
        : > "{{podman_socket_path}}"; \
    fi
