FROM registry.access.redhat.com/hi/core-runtime:latest-builder

USER root
RUN dnf -y install --setopt=install_weak_deps=False shadow-utils \
    && useradd --create-home --uid 1000 --home-dir /home/nonroot --shell /bin/bash nonroot \
    && dnf clean all
USER nonroot
