#!/usr/bin/env bash

set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
scratch_root="${project_root}/.scratch/feature-ci"
feature_project_root="${scratch_root}/project"
package_output_root="${scratch_root}/package"
shim_dir="${scratch_root}/bin"
workflow_base_image="${BASE_IMAGE:-fedora:42}"
workflow_remote_user="${REMOTE_USER:-root}"

dependents=(utils-agent utils-ops utils-human)
independent_features=(podman-outside-of-podman podman-in-podman devcontainer-cli opencode-server opencode-tui dotnet-aspire-cli)

err() {
    printf 'feature-ci: %s\n' "$*" >&2
}

usage() {
    cat <<'EOF'
Usage:
  bash scripts/feature-ci/run.sh prepare
  bash scripts/feature-ci/run.sh ci
  bash scripts/feature-ci/run.sh all
  bash scripts/feature-ci/run.sh publish-check
  bash scripts/feature-ci/run.sh feature <feature> [<feature>...]
  bash scripts/feature-ci/run.sh job <job-name>

Commands:
  prepare        Create the scratch project layout and Docker-to-Podman shim.
  ci             Run the current GitHub test workflow jobs locally.
  all            Run the local CI workflow plus the publish packaging check.
  publish-check  Package devcontainer features without publishing them.
  feature        Test one or more local features, including scenarios.
  job            Run one named workflow job or the local release check.

Known jobs:
  test-devcontainer-config
  test-fedora-dnf-repo
  test-utils-core
  test-utils-core-dependents
  test-autogenerated-independent
  test-podman-in-podman-scenarios
  deploy
EOF
}

ensure_prerequisites() {
    local tool

    for tool in bash devcontainer jq podman; do
        if ! command -v "${tool}" >/dev/null 2>&1; then
            err "missing required tool: ${tool}"
            exit 1
        fi
    done
}

ensure_docker_shim() {
    mkdir -p "${shim_dir}"

    cat >"${shim_dir}/docker" <<'EOF'
#!/usr/bin/env bash
exec podman "$@"
EOF

    chmod +x "${shim_dir}/docker"
    export PATH="${shim_dir}:${PATH}"
}

prepare_feature_project() {
    mkdir -p "${feature_project_root}"
    rm -rf "${feature_project_root}/src" "${feature_project_root}/test"
    ln -s "${project_root}/devcontainer-features" "${feature_project_root}/src"
    ln -s "${project_root}/test" "${feature_project_root}/test"
}

prepare_feature_runtime() {
    local podman_socket_path

    export FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
    export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-${scratch_root}/xdg}"
    podman_socket_path="${XDG_RUNTIME_DIR}/podman/podman.sock"

    mkdir -p "${XDG_RUNTIME_DIR}/podman"

    if [ ! -S "${podman_socket_path}" ]; then
        rm -f "${podman_socket_path}"
        : > "${podman_socket_path}"
    fi
}

prepare() {
    ensure_prerequisites
    ensure_docker_shim
    prepare_feature_project
    prepare_feature_runtime
}

run_repo_test() {
    local script_path="$1"

    (cd "${project_root}" && bash "${script_path}")
}

run_autogenerated_feature_test() {
    local feature_name="$1"

    prepare
    devcontainer features test \
        --project-folder "${feature_project_root}" \
        --skip-scenarios \
        --skip-duplicated \
        --base-image "${workflow_base_image}" \
        --remote-user "${workflow_remote_user}" \
        -f "${feature_name}"
}

run_feature_test() {
    prepare
    devcontainer features test \
        --project-folder "${feature_project_root}" \
        --skip-duplicated \
        --base-image "${workflow_base_image}" \
        --remote-user "${workflow_remote_user}" \
        -f "$@"
}

run_podman_in_podman_scenario() {
    prepare
    devcontainer features test \
        --project-folder "${feature_project_root}" \
        --skip-autogenerated \
        --skip-duplicated \
        --base-image "${workflow_base_image}" \
        --remote-user "${workflow_remote_user}" \
        -f podman-in-podman \
        --filter uid-65532
}

run_publish_check() {
    ensure_prerequisites
    rm -rf "${package_output_root}"
    devcontainer features package \
        "${project_root}/devcontainer-features" \
        --output-folder "${package_output_root}" \
        --force-clean-output-folder
    test -f "${package_output_root}/devcontainer-collection.json"
}

run_ci() {
    local feature_name

    run_repo_test test/devcontainer-config/test.sh
    run_repo_test test/fedora-dnf-repo/test.sh
    run_autogenerated_feature_test utils-core

    for feature_name in "${dependents[@]}"; do
        run_autogenerated_feature_test "${feature_name}"
    done

    for feature_name in "${independent_features[@]}"; do
        run_autogenerated_feature_test "${feature_name}"
    done

    run_podman_in_podman_scenario
}

run_job() {
    local job_name="$1"
    local feature_name

    case "${job_name}" in
        test-devcontainer-config)
            run_repo_test test/devcontainer-config/test.sh
            ;;
        test-fedora-dnf-repo)
            run_repo_test test/fedora-dnf-repo/test.sh
            ;;
        test-utils-core)
            run_autogenerated_feature_test utils-core
            ;;
        test-utils-core-dependents)
            for feature_name in "${dependents[@]}"; do
                run_autogenerated_feature_test "${feature_name}"
            done
            ;;
        test-autogenerated-independent)
            for feature_name in "${independent_features[@]}"; do
                run_autogenerated_feature_test "${feature_name}"
            done
            ;;
        test-podman-in-podman-scenarios)
            run_podman_in_podman_scenario
            ;;
        deploy)
            run_publish_check
            ;;
        *)
            err "unknown job: ${job_name}"
            usage
            exit 1
            ;;
    esac
}

command_name="${1:-all}"

case "${command_name}" in
    prepare)
        prepare
        ;;
    ci)
        run_ci
        ;;
    all)
        run_ci
        run_publish_check
        ;;
    publish-check)
        run_publish_check
        ;;
    feature)
        shift || true
        if [ "$#" -eq 0 ]; then
            err "feature requires at least one feature name"
            usage
            exit 1
        fi
        run_feature_test "$@"
        ;;
    job)
        shift || true
        if [ "$#" -ne 1 ]; then
            err "job requires exactly one job name"
            usage
            exit 1
        fi
        run_job "$1"
        ;;
    -h|--help|help)
        usage
        ;;
    *)
        err "unknown command: ${command_name}"
        usage
        exit 1
        ;;
esac
