FROM registry.access.redhat.com/hi/core-runtime:latest-builder

USER root

RUN dnf -y install --setopt=install_weak_deps=False shadow-utils \
    && dnf clean all \
    && useradd --create-home --home-dir /home/nonroot --shell /bin/sh nonroot \
    && install -d -o nonroot -g nonroot /var/cache/homebrew-shared \
    && rm -rf /var/cache/dnf

USER nonroot
