FROM registry.access.redhat.com/hi/core-runtime:latest-builder

USER root

RUN dnf -y install --setopt=install_weak_deps=False shadow-utils \
    && dnf clean all \
    && useradd --create-home --home-dir /home/nonroot --shell /bin/sh nonroot \
    && install -d -o nonroot -g nonroot /var/cache/homebrew-shared

COPY devcontainer-features/src/homebrew-install /tmp/homebrew-install

RUN USERNAME=nonroot \
        CACHE_DIRECTORY=/var/cache/homebrew-shared \
        CLEANUP_HOMEBREW=false \
        /bin/sh /tmp/homebrew-install/install.sh \
    && rm -rf /tmp/homebrew-install \
    && chown -R root:root /home/linuxbrew/.linuxbrew /var/cache/homebrew-shared \
    && dnf clean all \
    && rm -rf /var/cache/dnf
