FROM ghcr.io/jonathan-tyler/containers/core-runtime:latest-homebrew AS builder

USER root

RUN chown -R nonroot:nonroot /home/linuxbrew/.linuxbrew

USER nonroot

RUN /home/linuxbrew/.linuxbrew/bin/brew install squid \
    && /home/linuxbrew/.linuxbrew/bin/brew cleanup --prune=all --scrub

FROM registry.access.redhat.com/hi/core-runtime:latest

COPY --from=builder --chown=65532:65532 /home/linuxbrew/.linuxbrew /home/linuxbrew/.linuxbrew
COPY squid.conf /etc/squid/squid.conf
COPY allowed-domains.txt /etc/squid/allowed-domains.txt

ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH

USER 65532

EXPOSE 3128

CMD ["/home/linuxbrew/.linuxbrew/opt/squid/sbin/squid", "-N", "-f", "/etc/squid/squid.conf", "-d", "1"]
