FROM registry.access.redhat.com/hi/core-runtime:latest

RUN dnf -y install --setopt=install_weak_deps=False squid \
    && dnf clean all

COPY squid.conf /etc/squid/squid.conf

EXPOSE 3128

CMD ["squid", "-N", "-f", "/etc/squid/squid.conf", "-d", "1"]
