http_port 3128
visible_hostname squid

acl allowed_domains dstdomain "/etc/squid/allowed-domains.txt"
acl literal_ip url_regex -i ^https?://((([0-9]{1,3}\.){3}[0-9]{1,3})|\[[0-9A-Fa-f:]+\])(:[0-9]+)?(/|$)
acl SSL_ports port 443
acl Safe_ports port 80 443 1025-65535
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny literal_ip
http_access allow allowed_domains
http_access deny all
